### ISSUE TITLE
Always get "Invalid Tesseract version" when tesseract not exit as 0

### ISSUE THREAD

**Issue by STRRL** [thomasgruebl/rusty-tesseract#10]
It's better to carry out the exact  exitcode when tesseract does not work as expected.

https://github.com/thomasgruebl/rusty-tesseract/blob/4a0c3da00cd38b8157e833ea0547c72df8e0cbb7/src/tesseract/command.rs#L61-L64

**Comment by thomasgruebl** [comment]
Hi, thanks for raising this issue.

I've replaced the VersionError with a new CommandExitStatusError which displays the status code as well as the underlying error message coming from the std::process::Command struct.

**Comment by STRRL** [comment]
Awesome!
