### ISSUE TITLE
which Tesseract should I use?

### ISSUE THREAD

**Issue by Raj2032** [thomasgruebl/rusty-tesseract#18]
Hi I am a bit confused with this crate and the other tesseract crate:

https://crates.io/crates/tesseract

which one should I use?

**Comment by thomasgruebl** [comment]
Hi, the two crates have been developed independently from each other. You may use either one, whichever works best for you.

**Comment by Raj2032** [comment]
@thomasgruebl Thanks mate and I want to know some things, in your current crate:
1. this is just a bindings to tesseract library?
2. Is your crate still maintained?
3. Is it fast on a raspberry pi and alternative mini computers using risc-v processors?

**Comment by thomasgruebl** [comment]
1. Yes
2. Yes
3. This has not been tested, but I would say it should be reasonably fast.

**Comment by Raj2032** [comment]
@thomasgruebl THanks mate
