### ISSUE TITLE
Cargo warns "ignoring invalid dependency `rusty-tesseract` which is missing a lib target"

### ISSUE THREAD

**Issue by ecashin** [thomasgruebl/rusty-tesseract#2]
Hello and thanks for making rusty-tesseract.

I was getting started by doing `cargo add rusty-tesseract` or `cargo rm rusty-tesseract; cargo add rusty_tesseract` and then doing `use rusty_tesseract::Image;` in my `main.rs`.

But `cargo build` warns me that it's ignoring rusty-tesseract, because it has no library target in its `Cargo.toml`.

**Comment by ecashin** [comment]
These changes seem to help: #3

**Comment by thomasgruebl** [comment]
updated files accordingly.
