### ISSUE TITLE
disable log

### ISSUE THREAD

**Issue by louis030195** [thomasgruebl/rusty-tesseract#20]
hey great lib thanks!

trying to remove these logs:

>Tesseract Command: tesseract /var/folders/hq/swhzs3js29z7mb5b7ycnjcnm0000gn/T/rusty-tesseractltcabH.png stdout -l eng --dpi 150 --psm 3 --oem 3

only happen in dev mode it seem, still want to remove from dev mode, any idea how?

**Comment by louis030195** [comment]
https://github.com/thomasgruebl/rusty-tesseract/blob/2db428d93c4ed5aebdfeda57cfb2856fa94a5aee/src/tesseract/command.rs#L74

:'(

not sure what are best practices

**Comment by thomasgruebl** [comment]
Hey,

thanks for raising this issue. Are you just trying to prevent this line from being displayed? You may just comment the line with //

**Comment by louis030195** [comment]
did this

```rs
builder
  .filter(None, LevelFilter::Info)
  .filter_module("tokenizers", LevelFilter::Error)
  .filter_module("rusty_tesseract", LevelFilter::Error)
  .filter_module("symphonia", LevelFilter::Error);

```
